{{- if .Values.features.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: financial-poc-secrets
type: Opaque
data:
  # Add your secrets here or pass via --set
  # keys must be base64 encoded if not using stringData
  # stringData:
  #   API_KEY: "secret"
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
