"""add_reasoning_events_and_transitions

Revision ID: 0685d70898ee
Revises: fdd7cb4f4e70
Create Date: 2026-02-06 00:12:44.853743

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0685d70898ee"
down_revision: str | Sequence[str] | None = "fdd7cb4f4e70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("reasoning_events", sa.JSON(), nullable=True))
    op.add_column("messages", sa.Column("agent_transitions", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "agent_transitions")
    op.drop_column("messages", "reasoning_events")
    # ### end Alembic commands ###
