"""add_thread_id_to_documents

Revision ID: 5a2c6d7e8f9a
Revises: 0685d70898ee
Create Date: 2026-02-07 22:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a2c6d7e8f9a"
down_revision: str | None = "0685d70898ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("thread_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, "documents", "conversations", ["thread_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "thread_id")
    # ### end Alembic commands ###
